### ISSUE TITLE
Doesn't create a release-tag for minor versions

### ISSUE THREAD

**Issue by koenthefreeze** [iamludal/semantic-release-tags#1]
This plugin will create tags for minor and major versions according to the readme. However, it only creates a tag for major versions.

**Comment by iamludal** [comment]
Hi @koenthefreeze, thanks for your issue, you're totally right. I'm going to fix this in the next days. :)

**Comment by iamludal** [comment]
The issue has been solved by 192dcb9a32639fc6e8998a1b94184bf3424e8e71.
